### ISSUE TITLE
sudo python /home/pi/tyos/src/main.py 

### ISSUE THREAD

**Issue by oaf2015** [spadgenske/TYOS#1]
When I run sudo python /home/pi/tyos/src/main.py it does nothing. I am doing it all SSH. I appreciate your help. How long does it take or should I wait? Cou it be because I am using a fona 3G? If so, what do you recommend updating and which .py file? Main.py?

**Comment by tyspa1** [comment]
Do you get an error message? It should be printed out or appear in a file in `/home/pi/tyos/logs/tyos.log`. Are you using a TFT touchscreen? If not TYOS will not be displayed unless you change the software. Not sure about the 3G Fona, it may or may not work I need to see a error message first.

**Comment by oaf2015** [comment]
![snap 2017-03-21 at 17 27 02](https://cloud.githubusercontent.com/assets/21084440/24171662/b72078bc-0e5b-11e7-81aa-45cfb94e40bd.png)

**Comment by oaf2015** [comment]
that is what I get when I CTRL Z

**Comment by oaf2015** [comment]
Also I am unable to send the fona 3g AT commands

**Comment by tyspa1** [comment]
The code that is trying to communicate with the Fona is failing, better check to make sure you can communicate with the Fona with minicom or something otherwise TYOS will also fail.

**Comment by oaf2015** [comment]
![snap 2017-03-21 at 17 36 30](https://cloud.githubusercontent.com/assets/21084440/24171981/f6a7da2e-0e5c-11e7-9e72-160248b15d5a.png)

**Comment by oaf2015** [comment]
notice the offline message on bottom right. It is a pi3 should I comment or activate the serial, UART, etc?

**Comment by tyspa1** [comment]
The serial port should be disabled in rasp-config. (https://www.instructables.com/id/Build-Your-Own-Smartphone/step6/Setup-SD-Card/) If you type "AT" (nothing may appear on sceen) and press enter do you get "OK" back? If you don't you need to check your connections and make sure the serial port is setup properly.

**Comment by oaf2015** [comment]
![snap 2017-03-21 at 17 48 34](https://cloud.githubusercontent.com/assets/21084440/24172462/a33dfa06-0e5e-11e7-8714-dfd33b8d6aef.png)

**Comment by oaf2015** [comment]
I am going to re-image and start from the beginning.

**Comment by oaf2015** [comment]
When it comes to the minicom portion, I am going to disable the serial on the raspi-config and reboot. If minicom still shows ttyAMA0 offline, AT is not visible and OK is not received back, what do you recommend me doing?
